package old_attempts;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class Alison {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void auth() {
    // Test name: Auth
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://alison.com/");
    // 2 | setWindowSize | 1854x1048 |
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    driver.manage().window().setSize(new Dimension(1854, 1048));
    // 3 | click | linkText=Log In |

    WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log In")));
    loginButton.click();
//    driver.findElement(By.linkText("Log In")).click();
    // 4 | click | name=email |
    try {
      Thread.sleep(5000); // Wait for 5 seconds for the page to stabilize
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.name("email")).click();
    // 5 | type | name=email | radqueen.nhapulo@gmail.com
    driver.findElement(By.name("email")).sendKeys("radqueen.nhapulo@gmail.com");
    // 6 | click | name=login-form | 
    driver.findElement(By.name("login-form")).click();
    // 7 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 8 | type | name=password | AkdarNhapulo
    driver.findElement(By.name("password")).sendKeys("AkdarNhapulo");
    // 9 | click | css=.input-field:nth-child(3) > .icon-hide-password | 
    driver.findElement(By.cssSelector(".input-field:nth-child(3) > .icon-hide-password")).click();
    // 10 | click | css=.form-checkbox | 
    driver.findElement(By.cssSelector(".form-checkbox")).click();
    // 11 | click | css=.login__bottom:nth-child(7) .submit-login | 
    driver.findElement(By.cssSelector(".login__bottom:nth-child(7) .submit-login")).click();
    // 12 | click | id=ab-continue | 
    driver.findElement(By.id("ab-continue")).click();
    // 13 | mouseOver | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".tw-w-12"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | mouseOver | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".tw-w-12"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | mouseOut | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | css=.mat-tooltip-trigger > .ng-tns-c1065955076-1 | 
    driver.findElement(By.cssSelector(".mat-tooltip-trigger > .ng-tns-c1065955076-1")).click();
    // 18 | click | id=mat-input-0 | 
    driver.findElement(By.id("mat-input-0")).click();
    // 19 | type | id=mat-input-0 | New Title
    driver.findElement(By.id("mat-input-0")).sendKeys("New Title");
    // 20 | click | id=mat-input-1 | 
    driver.findElement(By.id("mat-input-1")).click();
    // 21 | type | id=mat-input-1 | This is my note
    driver.findElement(By.id("mat-input-1")).sendKeys("This is my note");
    // 22 | click | css=.btn-save > .mat-button-wrapper | 
    driver.findElement(By.cssSelector(".btn-save > .mat-button-wrapper")).click();
  }
}
