package old_attempts;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class CommentTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void comment() {
    // Test name: comment
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.flickr.com/");
    // 2 | setWindowSize | 680x697 |  | 
    driver.manage().window().setSize(new Dimension(680, 697));
    // 3 | mouseOver | id=yui_3_16_0_1_1744665831786_614 |  | 
    {
      WebElement element = driver.findElement(By.id("yui_3_16_0_1_1744665831786_614"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=yui_3_16_0_1_1744665831786_487 |  | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_487")).click();
    // 5 | click | id=yui_3_16_0_1_1744665831786_1037 |  | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_1037")).click();
    // 6 | mouseOver | css=#yui_3_16_0_1_1744665831786_3139 .overlay |  | 
    {
      WebElement element = driver.findElement(By.cssSelector("#yui_3_16_0_1_1744665831786_3139 .overlay"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseOut | id=yui_3_16_0_1_1744665831786_5192 |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 8 | click | id=yui_3_16_0_1_1744665831786_5307 |  | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_5307")).click();
    // 9 | mouseOver | id=yui_3_16_0_1_1744665831786_6529 |  | 
    {
      WebElement element = driver.findElement(By.id("yui_3_16_0_1_1744665831786_6529"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | click | id=yui_3_16_0_1_1744665831786_7499 |  | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_7499")).click();
    // 11 | type | id=yui_3_16_0_1_1744665831786_7499 | Wonderful!! | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_7499")).sendKeys("Wonderful!!");
    // 12 | click | id=yui_3_16_0_1_1744665831786_7512 |  | 
    driver.findElement(By.id("yui_3_16_0_1_1744665831786_7512")).click();
  }
}
