package old_attempts;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LanguageCHangeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void languageCHange() {
    // Test name: languageCHange
    // Step # | name | target | value
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    // 1 | open | / | 
    driver.get("https://alison.com/");
    // 2 | setWindowSize | 1854x1048 | 
    driver.manage().window().setSize(new Dimension(1854, 1048));

    try {
      Thread.sleep(5000); // Wait for 5 seconds for the page to stabilize
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 3 | click | linkText=Log In | 
    WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log In")));
    loginButton.click();

    try {
      Thread.sleep(5000); // Wait for 5 seconds for the page to stabilize
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 4 | click | name=email | 
    driver.findElement(By.name("email")).click();
    // 5 | type | name=email | radqueen.nhapulo@gmail.com
    driver.findElement(By.name("email")).sendKeys("radqueen.nhapulo@gmail.com");
    // 6 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 7 | type | name=password | AkdarNhapulo
    driver.findElement(By.name("password")).sendKeys("AkdarNhapulo");
    // 8 | click | css=.input-field:nth-child(3) > .icon-hide-password | 
    driver.findElement(By.cssSelector(".input-field:nth-child(3) > .icon-hide-password")).click();
    // 9 | click | css=.form-checkbox | 
    driver.findElement(By.cssSelector(".form-checkbox")).click();
    // 10 | click | css=.login__bottom:nth-child(7) .submit-login | 
    driver.findElement(By.cssSelector(".login__bottom:nth-child(7) .submit-login")).click();
    // 11 | click | id=ab-continue | 
    WebElement continueButton = wait.until(ExpectedConditions.elementToBeClickable(By.id("ab-continue")));
    continueButton.click();
    // 12 | click | css=.head__user-img > .ng-tns-c479218729-0 | 
    driver.findElement(By.cssSelector(".head__user-img > .ng-tns-c479218729-0")).click();
    // 13 | click | css=div:nth-child(1) > .user-menu__item > h5 | 
    driver.findElement(By.cssSelector("div:nth-child(1) > .user-menu__item > h5")).click();
    // 14 | click | css=.user-menu__item:nth-child(2) > h5 | 
    driver.findElement(By.cssSelector(".user-menu__item:nth-child(2) > h5")).click();
  }
}
