package old_attempts;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logout() {
    // Test name: logout
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://alison.com/");
    // 2 | setWindowSize | 784x701 | 
    driver.manage().window().setSize(new Dimension(784, 701));
    // 3 | click | linkText=Log In | 
    driver.findElement(By.linkText("Log In")).click();
    // 4 | click | name=email | 
    driver.findElement(By.name("email")).click();
    // 5 | type | name=email | radqueen.nhapulo@gmail.com
    driver.findElement(By.name("email")).sendKeys("radqueen.nhapulo@gmail.com");
    // 6 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 7 | type | name=password | AkdarNhapulo
    driver.findElement(By.name("password")).sendKeys("AkdarNhapulo");
    // 9 | click | css=.form-checkbox | 
    driver.findElement(By.cssSelector(".form-checkbox")).click();
    // 10 | click | css=.login__bottom:nth-child(7) .submit-login | 
    driver.findElement(By.cssSelector(".login__bottom:nth-child(7) .submit-login")).click();
    // 11 | mouseOver | id=ab-continue | 
    {
      WebElement element = driver.findElement(By.id("ab-continue"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | id=nsp | 
    driver.findElement(By.id("nsp")).click();
    // 13 | click | id=ab-continue | 
    driver.findElement(By.id("ab-continue")).click();
    // 14 | click | css=.head__user-img > .ng-tns-c479218729-0 | 
    driver.findElement(By.cssSelector(".head__user-img > .ng-tns-c479218729-0")).click();
    // 15 | click | css=.ng-star-inserted:nth-child(10) h5 | 
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(10) h5")).click();
  }
}
