// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

import java.time.Duration;
//@RunWith(JUnit4.class)
public class AuthTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void auth() {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    driver.get("https://www.flickr.com/");
    driver.manage().window().setSize(new Dimension(680, 696));

    try {
      WebElement cookieBanner = wait.until(ExpectedConditions.presenceOfElementLocated(By.id("pop-div02135150987884522")));

      WebElement acceptCookiesButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".accept-cookie-button"))); // Change selector if needed
      ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", acceptCookiesButton);
      acceptCookiesButton.click();
      wait.until(ExpectedConditions.invisibilityOf(cookieBanner));
    } catch (Exception e) {
      System.out.println("No cookie banner found or already dismissed.");
    }

    WebElement iconButton = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".icon-5")));
    iconButton.click();
    driver.findElement(By.cssSelector(".explore-link-mobile")).click();
    driver.findElement(By.id("login-email")).click();
    driver.findElement(By.id("login-email")).sendKeys("radqueen.nhapulo@gmail.com");
    driver.findElement(By.cssSelector(".mt-5")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mt-5"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    WebElement submitButton = wait.until(ExpectedConditions.elementToBeClickable(By.id("login-password")));
    submitButton.sendKeys("AkdarNhapulo");
    driver.findElement(By.cssSelector(".mt-5")).click();
  }
}
