// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Comment2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void comment2() {
    // Test name: comment2
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.flickr.com/");
    // 2 | setWindowSize | 680x698 | 
    driver.manage().window().setSize(new Dimension(680, 698));
    // 3 | click | id=yui_3_16_0_1_1744707976712_939 | 
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_939")).click();
    // 4 | click | id=yui_3_16_0_1_1744707976712_969 | 
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_969")).click();
    // 5 | mouseOver | css=#yui_3_16_0_1_1744707976712_2982 .overlay | 
    {
      WebElement element = driver.findElement(By.cssSelector("#yui_3_16_0_1_1744707976712_2982 .overlay"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 6 | mouseOut | id=yui_3_16_0_1_1744707976712_4912 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 7 | click | id=yui_3_16_0_1_1744707976712_4984 | 
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_4984")).click();
    // 8 | runScript | window.scrollTo(0,473) | 
    js.executeScript("window.scrollTo(0,473)");
    // 9 | click | id=yui_3_16_0_1_1744707976712_7274 | 
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_7274")).click();
    // 10 | type | id=yui_3_16_0_1_1744707976712_7274 | Wow
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_7274")).sendKeys("Wow");
    // 11 | click | id=yui_3_16_0_1_1744707976712_7286 | 
    driver.findElement(By.id("yui_3_16_0_1_1744707976712_7286")).click();
  }
}
