// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewSiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newSite() {

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    driver.get("https://alison.com/");
    driver.manage().window().setSize(new Dimension(1200, 800));

    try {
      Thread.sleep(5000); // Wait for 5 seconds for the page to stabilize
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // Test name: newSite
    // Step # | name | target | value
    // 1 | click | linkText=Log In |
    WebElement loginButton = wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log In")));
    loginButton.click();
    // 2 | click | name=email |
    try {
      Thread.sleep(5000); // Wait for 5 seconds for the page to stabilize
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.name("email")).click();
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    // 4 | type | name=email | radqueen.nhapulo@gmail.com
    driver.findElement(By.name("email")).sendKeys("radqueen.nhapulo@gmail.com");
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 6 | type | name=password | AkdarNhapulo
    driver.findElement(By.name("password")).sendKeys("AkdarNhapulo");
    // 7 | click | css=.login__bottom:nth-child(7) .submit-login | 
    driver.findElement(By.cssSelector(".login__bottom:nth-child(7) .submit-login")).click();
    // 8 | click | id=ab-continue |
    WebElement continueButton = wait.until(ExpectedConditions.elementToBeClickable(By.id("ab-continue")));
    continueButton.click();
    // 9 | mouseOver | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".tw-w-12"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=.tw-w-12 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.mat-tooltip-trigger > .ng-tns-c1303978260-1 | 
    driver.findElement(By.cssSelector(".mat-tooltip-trigger > .ng-tns-c1303978260-1")).click();
    // 12 | click | id=mat-input-1 | 
    driver.findElement(By.id("mat-input-1")).click();
    // 13 | type | id=mat-input-1 | This is my new note
    driver.findElement(By.id("mat-input-1")).sendKeys("This is my new note");
    // 14 | click | id=mat-input-0 | 
    driver.findElement(By.id("mat-input-0")).click();
    // 15 | type | id=mat-input-0 | It has a titile
    driver.findElement(By.id("mat-input-0")).sendKeys("It has a titile");
    // 16 | click | css=.btn-save | 
    driver.findElement(By.cssSelector(".btn-save")).click();
    // 17 | click | css=.notes-panel-backdrob | 
    driver.findElement(By.cssSelector(".notes-panel-backdrob")).click();
    // 18 | open | https://alison.com/ | 
    driver.get("https://alison.com/");
  }
}
